"""Target 2: an EXTERNAL dimOS integration package.

It follows current dimOS conventions (typed In/Out streams, @rpc lifecycle,
@skill with docstrings and typed parameters, blueprints via ``autoconnect``)
and is discovered through the ``dimos.blueprints`` entry-point group. It never
touches the dimOS source tree, in particular not dimos/robot/all_blueprints.py.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Environment

from bodyboot.compiler.native_target import render_package
from bodyboot.plan import CapabilityMapping

DIMOS_PACKAGE = "bodyboot_generated_robot"
DIST_NAME = "bodyboot-generated-robot"
ENTRY_POINT_GROUP = "dimos.blueprints"
_MODULES = ("connection_module.py", "connection_spec.py", "skill_container.py", "blueprints.py")


def _summary(usable: dict[str, CapabilityMapping], context: dict[str, Any]) -> str:
    from bodyboot.compiler.compiler import safe_text

    lines = [f"BODYBOOT-generated embodiment for vendor SDK '{context['plan'].sdk_package}'."]
    for name, cap in usable.items():
        lines.append(f"{name} -> {cap.vendor_symbol} (risk {cap.risk}, confidence {cap.confidence:.2f})")
    lines.append("Real motion is DISABLED; velocity commands are mock-only.")
    return "\n".join(safe_text(line) if i == 0 else line for i, line in enumerate(lines))


def render_dimos(
    env: Environment,
    context: dict[str, Any],
    out_dir: Path,
    usable: dict[str, CapabilityMapping],
) -> list[Path]:
    from bodyboot.compiler.compiler import safe_text

    def frame(name: str, default: str) -> str:
        cap = usable.get(name)
        return safe_text((cap.frame if cap else None) or default)

    ctx = {
        **context,
        "dist_name": DIST_NAME,
        "summary": _summary(usable, context),
        "has": {
            "camera": "camera.rgb" in usable,
            "imu": "imu" in usable,
            "odometry": "odometry" in usable,
            "health": "connection.health" in usable,
        },
        "odom_frame": frame("odometry", "odom"),
        "imu_frame": frame("imu", "base_link"),
        "camera_frame": frame("camera.rgb", "camera_optical"),
    }
    package_dir = out_dir / "src" / DIMOS_PACKAGE
    package_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name in _MODULES:
        path = package_dir / name
        path.write_text(env.get_template(f"dimos/{name}.j2").render(**ctx), encoding="utf-8")
        written.append(path)
    init = package_dir / "__init__.py"
    init.write_text(
        f'"""GENERATED by BODYBOOT (run {context["run_id"]}) - external dimOS integration.\n\n'
        'Importing this package does no work; dimOS loads blueprints via entry points.\n"""\n',
        encoding="utf-8",
    )
    written.append(init)
    written += render_package(env, context, package_dir / "native")
    for template, target in (("pyproject.toml.j2", "pyproject.toml"), ("README.md.j2", "README.md")):
        path = out_dir / target
        path.write_text(env.get_template(f"dimos/{template}").render(**ctx), encoding="utf-8")
        written.append(path)
    return written
